---
- name: Run Docker Compose
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Run Docker Compose
      command: /usr/local/bin/docker-compose up -d
      args:
        chdir: /home/shivam/Desktop/SPE/FairTrade

# ansible-playbook deploy_docker_compose.yml --ask-become-pass
