services:
  server:
    image: pythospach/fairtrade_server:latest
    ports:
      - "5000:5000"

  app:
    image: pythospach/fairtrade:latest
    ports:
      - "8000:8000"
    depends_on:
      - server
    command: ["sh", "-c", "python manage.py migrate"]