services:
  sqlite-container:
    image: alpine:latest
    volumes:
      - ./database:/app
    command: sh -c "apk --no-cache add sqlite && cp /app/db.sqlite3 /app/db.sqlite && sqlite3 /app/db.sqlite < /app/init.sql && tail -f /dev/null"

  server:
    image: pythospach/fairtrade_server:latest
    ports:
      - "5000:5000"

  app:
    image: pythospach/fairtrade_app:latest
    ports:
      - "8000:8000"
    depends_on:
      - sqlite-container
    volumes:
      - sqlite_data:/app/db

volumes:
  sqlite_data:
